export const products: Product[] = [
  {
    id: "1",
    name: "Ocean Paradise 2",
    slug: "ocean-paradise-2",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk ocean paradise 2 van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 79.5,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Ocean Paradise 2", "Ocean Paradise 4"] }],
    collectionId: "10",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/schotels",
    recipes: [
      {
        title: "Ocean Paradise 2 – eenvoudig recept",
        ingredients: ["Ocean Paradise 2", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["ocean-paradise-2"],
      },
    ],
  },
  {
    id: "2",
    name: "Schmidt Royale 2",
    slug: "schmidt-royale-2",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk schmidt royale 2 van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 99.5,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Schmidt Royale 2", "Schmidt Royale 4"] }],
    collectionId: "10",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/schotels",
    recipes: [
      {
        title: "Schmidt Royale 2 – eenvoudig recept",
        ingredients: ["Schmidt Royale 2", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["schmidt-royale-2"],
      },
    ],
  },
  {
    id: "3",
    name: "Amuse festijn",
    slug: "amuse-festijn",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk amuse festijn van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 49.5,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Amuse festijn"] }],
    collectionId: "10",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/schotels",
    recipes: [
      {
        title: "Amuse festijn – eenvoudig recept",
        ingredients: ["Amuse festijn", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["amuse-festijn"],
      },
    ],
  },
  {
    id: "4",
    name: "Saladeset",
    slug: "saladeset",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk saladeset van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 9.95,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Saladeset", "Saladetrio"] }],
    collectionId: "10",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/schotels",
    recipes: [
      {
        title: "Saladeset – eenvoudig recept",
        ingredients: ["Saladeset", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["saladeset"],
      },
    ],
  },
  {
    id: "5",
    name: "Dorade",
    slug: "dorade",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk dorade van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 8.4,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Royal filet 1 pers.", "Royal groot heel"] }],
    collectionId: "2",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/verse-vis",
    recipes: [
      {
        title: "Dorade – eenvoudig recept",
        ingredients: ["Dorade", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["dorade"],
      },
    ],
  },
  {
    id: "6",
    name: "Forel",
    slug: "forel",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk forel van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 5.95,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Filet", "Heel"] }],
    collectionId: "2",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/verse-vis",
    recipes: [
      {
        title: "Forel – eenvoudig recept",
        ingredients: ["Forel", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["forel"],
      },
    ],
  },
  {
    id: "7",
    name: "Makreel",
    slug: "makreel",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk makreel van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 6.45,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Filet", "Heel"] }],
    collectionId: "2",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/verse-vis",
    recipes: [
      {
        title: "Makreel – eenvoudig recept",
        ingredients: ["Makreel", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["makreel"],
      },
    ],
  },
  {
    id: "8",
    name: "Tonijn",
    slug: "tonijn",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk tonijn van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 8,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Filet", "Voor sashimi"] }],
    collectionId: "2",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/verse-vis",
    recipes: [
      {
        title: "Tonijn – eenvoudig recept",
        ingredients: ["Tonijn", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["tonijn"],
      },
    ],
  },
  {
    id: "9",
    name: "Oesters",
    slug: "oesters",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk oesters van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 8.9,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Creuses Blanche de Normande", "Creuses Gillardeau"] }],
    collectionId: "3",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/schaal-en-schelpdieren",
    recipes: [
      {
        title: "Oesters – eenvoudig recept",
        ingredients: ["Oesters", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["oesters"],
      },
    ],
  },
  {
    id: "10",
    name: "Mosselen",
    slug: "mosselen",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk mosselen van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 16.95,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Zeeuwse Jumbo's", "Zeeuwse Supers"] }],
    collectionId: "3",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/schaal-en-schelpdieren",
    recipes: [
      {
        title: "Mosselen – eenvoudig recept",
        ingredients: ["Mosselen", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["mosselen"],
      },
    ],
  },
  {
    id: "11",
    name: "Langoustines",
    slug: "langoustines",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk langoustines van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 2.1,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Groot", "Klein"] }],
    collectionId: "3",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/schaal-en-schelpdieren",
    recipes: [
      {
        title: "Langoustines – eenvoudig recept",
        ingredients: ["Langoustines", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["langoustines"],
      },
    ],
  },
  {
    id: "12",
    name: "Vongole",
    slug: "vongole",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk vongole van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 32.5,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Vongole"] }],
    collectionId: "3",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/schaal-en-schelpdieren",
    recipes: [
      {
        title: "Vongole – eenvoudig recept",
        ingredients: ["Vongole", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["vongole"],
      },
    ],
  },
  {
    id: "13",
    name: "Ansjovis",
    slug: "ansjovis",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk ansjovis van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 5.5,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Filet naturel", "Spies met olijf"] }],
    collectionId: "8",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/delicatessen",
    recipes: [
      {
        title: "Ansjovis – eenvoudig recept",
        ingredients: ["Ansjovis", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["ansjovis"],
      },
    ],
  },
  {
    id: "14",
    name: "Garnalen Gemarineerd",
    slug: "garnalen-gemarineerd",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk garnalen gemarineerd van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 4.95,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Aioli", "French Garden"] }],
    collectionId: "8",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/delicatessen",
    recipes: [
      {
        title: "Garnalen Gemarineerd – eenvoudig recept",
        ingredients: ["Garnalen Gemarineerd", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["garnalen-gemarineerd"],
      },
    ],
  },
  {
    id: "15",
    name: "Haring",
    slug: "haring",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk haring van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 1.6,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Bokking", "Rolmops groot"] }],
    collectionId: "8",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/delicatessen",
    recipes: [
      {
        title: "Haring – eenvoudig recept",
        ingredients: ["Haring", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["haring"],
      },
    ],
  },
  {
    id: "16",
    name: "Paling",
    slug: "paling",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk paling van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 9.75,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Aalfilet gerookt", "Palingmootjes gerookt"] }],
    collectionId: "8",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/delicatessen",
    recipes: [
      {
        title: "Paling – eenvoudig recept",
        ingredients: ["Paling", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["paling"],
      },
    ],
  },
  {
    id: "17",
    name: "Dorade Provençaals",
    slug: "dorade-provencaals",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk dorade provençaals van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 2.95,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Dorade Provençaals"] }],
    collectionId: "4",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/kant-en-klaar",
    recipes: [
      {
        title: "Dorade Provençaals – eenvoudig recept",
        ingredients: ["Dorade Provençaals", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["dorade-provencaals"],
      },
    ],
  },
  {
    id: "18",
    name: "Spies garnalen",
    slug: "spies-garnalen",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk spies garnalen van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 2.95,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Spies garnalen"] }],
    collectionId: "4",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/kant-en-klaar",
    recipes: [
      {
        title: "Spies garnalen – eenvoudig recept",
        ingredients: ["Spies garnalen", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["spies-garnalen"],
      },
    ],
  },
  {
    id: "19",
    name: "Vispotje tomaat/paprika",
    slug: "vispotje-tomaat-paprika",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk vispotje tomaat/paprika van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 2.75,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Vispotje tomaat/paprika"] }],
    collectionId: "4",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/kant-en-klaar",
    recipes: [
      {
        title: "Vispotje tomaat/paprika – eenvoudig recept",
        ingredients: ["Vispotje tomaat/paprika", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["vispotje-tomaat-paprika"],
      },
    ],
  },
  {
    id: "20",
    name: "Quiche",
    slug: "quiche",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk quiche van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 9.9,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Quiche"] }],
    collectionId: "4",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/kant-en-klaar",
    recipes: [
      {
        title: "Quiche – eenvoudig recept",
        ingredients: ["Quiche", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["quiche"],
      },
    ],
  },
  {
    id: "21",
    name: "Jürgen Langbein bouillabaisse soep",
    slug: "jurgen-langbein-bouillabaisse-soep",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk jürgen langbein bouillabaisse soep van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 8.75,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Bouillabaisse soep"] }],
    collectionId: "12",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/conserven",
    recipes: [
      {
        title: "Jürgen Langbein bouillabaisse soep – eenvoudig recept",
        ingredients: ["Jürgen Langbein bouillabaisse soep", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["jurgen-langbein-bouillabaisse-soep"],
      },
    ],
  },
  {
    id: "22",
    name: "Crab Meat Claw",
    slug: "crab-meat-claw",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk crab meat claw van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 20.1,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Crab Meat Claw"] }],
    collectionId: "12",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/conserven",
    recipes: [
      {
        title: "Crab Meat Claw – eenvoudig recept",
        ingredients: ["Crab Meat Claw", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["crab-meat-claw"],
      },
    ],
  },
  {
    id: "23",
    name: "Inktvisinkt",
    slug: "inktvisinkt",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk inktvisinkt van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 2.15,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Inktvisinkt"] }],
    collectionId: "12",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/conserven",
    recipes: [
      {
        title: "Inktvisinkt – eenvoudig recept",
        ingredients: ["Inktvisinkt", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["inktvisinkt"],
      },
    ],
  },
  {
    id: "24",
    name: "Ansjovisfilet Codesa",
    slug: "ansjovisfilet-codesa",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk ansjovisfilet codesa van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 2.75,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Ansjovisfilet Codesa"] }],
    collectionId: "12",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/conserven",
    recipes: [
      {
        title: "Ansjovisfilet Codesa – eenvoudig recept",
        ingredients: ["Ansjovisfilet Codesa", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["ansjovisfilet-codesa"],
      },
    ],
  },
  {
    id: "25",
    name: "Fruits de mer",
    slug: "fruits-de-mer",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk fruits de mer van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 11.5,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Fruits de mer"] }],
    collectionId: "11",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/diepvries",
    recipes: [
      {
        title: "Fruits de mer – eenvoudig recept",
        ingredients: ["Fruits de mer", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["fruits-de-mer"],
      },
    ],
  },
  {
    id: "26",
    name: "Escargots",
    slug: "escargots",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk escargots van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 27.5,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Escargots"] }],
    collectionId: "11",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/diepvries",
    recipes: [
      {
        title: "Escargots – eenvoudig recept",
        ingredients: ["Escargots", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["escargots"],
      },
    ],
  },
  {
    id: "27",
    name: "Garnalen gepeld 30/40",
    slug: "garnalen-gepeld-30-40",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk garnalen gepeld 30/40 van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 17.5,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Gepeld 30/40"] }],
    collectionId: "11",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/diepvries",
    recipes: [
      {
        title: "Garnalen gepeld 30/40 – eenvoudig recept",
        ingredients: ["Garnalen gepeld 30/40", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["garnalen-gepeld-30-40"],
      },
    ],
  },
  {
    id: "28",
    name: "King crab poten",
    slug: "king-crab-poten",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk king crab poten van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 71.05,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["King crab poten"] }],
    collectionId: "11",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/diepvries",
    recipes: [
      {
        title: "King crab poten – eenvoudig recept",
        ingredients: ["King crab poten", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["king-crab-poten"],
      },
    ],
  },
  {
    id: "29",
    name: "Aioli Eyserhalte",
    slug: "aioli-eyserhalte",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk aioli eyserhalte van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 2.25,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Aioli Eyserhalte"] }],
    collectionId: "9",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/sauzen",
    recipes: [
      {
        title: "Aioli Eyserhalte – eenvoudig recept",
        ingredients: ["Aioli Eyserhalte", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["aioli-eyserhalte"],
      },
    ],
  },
  {
    id: "30",
    name: "Truffelmayonaise Eyserhalte",
    slug: "truffelmayonaise-eyserhalte",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk truffelmayonaise eyserhalte van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 2.25,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Truffelmayonaise Eyserhalte"] }],
    collectionId: "9",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/sauzen",
    recipes: [
      {
        title: "Truffelmayonaise Eyserhalte – eenvoudig recept",
        ingredients: ["Truffelmayonaise Eyserhalte", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["truffelmayonaise-eyserhalte"],
      },
    ],
  },
  {
    id: "31",
    name: "Kreeftensaus Eyserhalte",
    slug: "kreeftensaus-eyserhalte",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk kreeftensaus eyserhalte van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 12.95,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Kreeftensaus Eyserhalte"] }],
    collectionId: "9",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/sauzen",
    recipes: [
      {
        title: "Kreeftensaus Eyserhalte – eenvoudig recept",
        ingredients: ["Kreeftensaus Eyserhalte", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["kreeftensaus-eyserhalte"],
      },
    ],
  },
  {
    id: "32",
    name: "Tataki Saus",
    slug: "tataki-saus",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk tataki saus van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 6.45,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Tataki Saus"] }],
    collectionId: "9",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/sauzen",
    recipes: [
      {
        title: "Tataki Saus – eenvoudig recept",
        ingredients: ["Tataki Saus", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["tataki-saus"],
      },
    ],
  },
  {
    id: "33",
    name: "Cadeaukaart",
    slug: "cadeaukaart",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk cadeaukaart van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 25,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["€25", "€50"] }],
    collectionId: "15",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/diversen",
    recipes: [
      {
        title: "Cadeaukaart – eenvoudig recept",
        ingredients: ["Cadeaukaart", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["cadeaukaart"],
      },
    ],
  },
  {
    id: "34",
    name: "Crackers Italiaanse",
    slug: "crackers-italiaanse",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk crackers italiaanse van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 3.95,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Italiaanse crackers"] }],
    collectionId: "15",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/diversen",
    recipes: [
      {
        title: "Crackers Italiaanse – eenvoudig recept",
        ingredients: ["Crackers Italiaanse", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["crackers-italiaanse"],
      },
    ],
  },
  {
    id: "35",
    name: "Koffiebonen",
    slug: "koffiebonen",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk koffiebonen van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 41.95,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Koffiebonen"] }],
    collectionId: "15",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/diversen",
    recipes: [
      {
        title: "Koffiebonen – eenvoudig recept",
        ingredients: ["Koffiebonen", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["koffiebonen"],
      },
    ],
  },
  {
    id: "36",
    name: "Schmidt Originals Zeevis Kookboek",
    slug: "schmidt-originals-zeevis-kookboek",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk schmidt originals zeevis kookboek van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 14.5,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Schmidt Originals Zeevis Kookboek"] }],
    collectionId: "15",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/diversen",
    recipes: [
      {
        title: "Schmidt Originals Zeevis Kookboek – eenvoudig recept",
        ingredients: ["Schmidt Originals Zeevis Kookboek", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["schmidt-originals-zeevis-kookboek"],
      },
    ],
  },
  {
    id: "37",
    name: "Sushi box",
    slug: "sushi-box",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk sushi box van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 64.5,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Sushi box"] }],
    collectionId: "5",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/sushi-en-sashimi",
    recipes: [
      {
        title: "Sushi box – eenvoudig recept",
        ingredients: ["Sushi box", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["sushi-box"],
      },
    ],
  },
  {
    id: "38",
    name: "Tonijn voor sashimi",
    slug: "tonijn-voor-sashimi",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk tonijn voor sashimi van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 8,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Voor sashimi"] }],
    collectionId: "5",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/sushi-en-sashimi",
    recipes: [
      {
        title: "Tonijn voor sashimi – eenvoudig recept",
        ingredients: ["Tonijn voor sashimi", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["tonijn-voor-sashimi"],
      },
    ],
  },
  {
    id: "39",
    name: "Zalm voor sashimi",
    slug: "zalm-voor-sashimi",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk zalm voor sashimi van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 7.25,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Voor sashimi"] }],
    collectionId: "5",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/sushi-en-sashimi",
    recipes: [
      {
        title: "Zalm voor sashimi – eenvoudig recept",
        ingredients: ["Zalm voor sashimi", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["zalm-voor-sashimi"],
      },
    ],
  },
  {
    id: "40",
    name: "Wasabi Kizami",
    slug: "wasabi-kizami",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk wasabi kizami van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 2.5,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Wasabi Kizami"] }],
    collectionId: "5",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/sushi-en-sashimi",
    recipes: [
      {
        title: "Wasabi Kizami – eenvoudig recept",
        ingredients: ["Wasabi Kizami", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["wasabi-kizami"],
      },
    ],
  },
  {
    id: "41",
    name: "Extra vergine olijfolie",
    slug: "extra-vergine-olijfolie",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk extra vergine olijfolie van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 12.95,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Fles Italiaanse olijfolie"] }],
    collectionId: "6",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/olie-en-azijn",
    recipes: [
      {
        title: "Extra vergine olijfolie – eenvoudig recept",
        ingredients: ["Extra vergine olijfolie", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["extra-vergine-olijfolie"],
      },
    ],
  },
  {
    id: "42",
    name: "Blik Spaanse olijfolie",
    slug: "blik-spaanse-olijfolie",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk blik spaanse olijfolie van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 12.95,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Blik Spaanse olijfolie"] }],
    collectionId: "6",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/olie-en-azijn",
    recipes: [
      {
        title: "Blik Spaanse olijfolie – eenvoudig recept",
        ingredients: ["Blik Spaanse olijfolie", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["blik-spaanse-olijfolie"],
      },
    ],
  },
  {
    id: "43",
    name: "Royal Selection Black currant Vinegar",
    slug: "royal-selection-black-currant-vinegar",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk royal selection black currant vinegar van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 9.75,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Royal Selection Black currant Vinegar"] }],
    collectionId: "6",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/olie-en-azijn",
    recipes: [
      {
        title: "Royal Selection Black currant Vinegar – eenvoudig recept",
        ingredients: ["Royal Selection Black currant Vinegar", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["royal-selection-black-currant-vinegar"],
      },
    ],
  },
  {
    id: "44",
    name: "Balsamico 15 jaar",
    slug: "balsamico-15-jaar",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk balsamico 15 jaar van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 9.95,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Balsamico 15 jaar"] }],
    collectionId: "6",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/olie-en-azijn",
    recipes: [
      {
        title: "Balsamico 15 jaar – eenvoudig recept",
        ingredients: ["Balsamico 15 jaar", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["balsamico-15-jaar"],
      },
    ],
  },
  {
    id: "45",
    name: "Mosselkruiden",
    slug: "mosselkruiden",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk mosselkruiden van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 0.95,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Mosselkruiden"] }],
    collectionId: "13",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/kruiden-en-specerijen",
    recipes: [
      {
        title: "Mosselkruiden – eenvoudig recept",
        ingredients: ["Mosselkruiden", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["mosselkruiden"],
      },
    ],
  },
  {
    id: "46",
    name: "Piri Piri",
    slug: "piri-piri",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk piri piri van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 3.5,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Piri Piri"] }],
    collectionId: "13",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/kruiden-en-specerijen",
    recipes: [
      {
        title: "Piri Piri – eenvoudig recept",
        ingredients: ["Piri Piri", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["piri-piri"],
      },
    ],
  },
  {
    id: "47",
    name: "Morvandelles Courtbouillon",
    slug: "morvandelles-courtbouillon",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk morvandelles courtbouillon van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 3.5,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Courtbouillon"] }],
    collectionId: "13",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/kruiden-en-specerijen",
    recipes: [
      {
        title: "Morvandelles Courtbouillon – eenvoudig recept",
        ingredients: ["Morvandelles Courtbouillon", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["morvandelles-courtbouillon"],
      },
    ],
  },
  {
    id: "48",
    name: "Sal de Ibiza - klein",
    slug: "sal-de-ibiza---klein",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk sal de ibiza - klein van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 5.95,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Sal de Ibiza - klein"] }],
    collectionId: "13",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/kruiden-en-specerijen",
    recipes: [
      {
        title: "Sal de Ibiza - klein – eenvoudig recept",
        ingredients: ["Sal de Ibiza - klein", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["sal-de-ibiza---klein"],
      },
    ],
  },
  {
    id: "49",
    name: "Schmidt visfileermes",
    slug: "schmidt-visfileermes",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk schmidt visfileermes van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 44.95,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Schmidt visfileermes"] }],
    collectionId: "14",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/merchandise",
    recipes: [
      {
        title: "Schmidt visfileermes – eenvoudig recept",
        ingredients: ["Schmidt visfileermes", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["schmidt-visfileermes"],
      },
    ],
  },
  {
    id: "50",
    name: "Schmidt's zwarte sokken",
    slug: "schmidts-zwarte-sokken",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk schmidt's zwarte sokken van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 9.95,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Zwarte sokken"] }],
    collectionId: "14",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/merchandise",
    recipes: [
      {
        title: "Schmidt's zwarte sokken – eenvoudig recept",
        ingredients: ["Schmidt's zwarte sokken", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["schmidts-zwarte-sokken"],
      },
    ],
  },
  {
    id: "51",
    name: "Mosselpan",
    slug: "mosselpan",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk mosselpan van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 18.5,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Mosselpan"] }],
    collectionId: "14",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/merchandise",
    recipes: [
      {
        title: "Mosselpan – eenvoudig recept",
        ingredients: ["Mosselpan", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["mosselpan"],
      },
    ],
  },
  {
    id: "52",
    name: "Oesteropenerset",
    slug: "oesteropenerset",
    shortDescription: "Van Schmidt Zeevis – verse kwaliteit.",
    description: "Heerlijk oesteropenerset van Schmidt Zeevis. Bekijk het assortiment en bestel op onze webwinkel.",
    price: 14.5,
    image: "",
    thumbnails: [],
    rating: 4.5,
    reviewCount: 67,
    weight: "—",
    variants: [{ name: "Kies uw optie", options: ["Oesteropenerset"] }],
    collectionId: "14",
    seasonality: "available",
    allergens: [],
    nutritionalInfo: [
      { name: "Calorieën", value: "—" },
      { name: "Eiwitten", value: "—" },
      { name: "Vetten", value: "—" },
    ],
    seasonCalendar: defaultSeasonCalendar,
    externalUrl: "https://www.schmidtzeevis.nl/webwinkel/artikel/merchandise",
    recipes: [
      {
        title: "Oesteropenerset – eenvoudig recept",
        ingredients: ["Oesteropenerset", "Verse kruiden", "Zout en peper", "Olijfolie"],
        instructions: ["Bereid de ingrediënten voor.", "Volg de aanwijzingen op de verpakking of bereid naar wens.", "Serveer vers."],
        usedProducts: ["oesteropenerset"],
      },
    ],
  }
];
